<?php

function greeting_menu() {
    $items = [];
    $items['hello_friend'] = array(
        'title' => 'Hello Friend!',
        'page callback' => 'say_hello',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['goodbye'] = array(
        'title' => 'Goodbye Friend!',
        'page callback' => 'say_goodbye',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function say_hello(){
  return '<h1>HELLO FRIEND!</h1>';
}

function say_goodbye(){
  return '<h1>SMELL YA LATER!</h1>';
}

function greeting_user_login() {
  $_GET['destination'] = 'hello_friend';
}

function greeting_user_logout() {
  $_GET['destination'] = 'goodbye';
}
